wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.10.10
    start_time: 1684763844.356248
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      4: 3.10.10
      5: 0.13.5
      8:
      - 1
      - 2
      - 5
amp:
  desc: null
  value: true
batch_size:
  desc: null
  value: 1
epochs:
  desc: null
  value: 1
img_scale:
  desc: null
  value: 1.0
learning_rate:
  desc: null
  value: 1.0e-05
save_checkpoint:
  desc: null
  value: true
val_percent:
  desc: null
  value: 0.1
